config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'

  resources :users, only: [:index] do
    resources :categories, only: [:index, :show, :new, :create] do 
      resources :financial_transactions, only: [:index, :new, :create]
  end 
end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat_transact.rb
class CatTransact < ApplicationRecord
  belongs_to :category
  belongs_to :financial_transaction
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :icon
  has_many :cat_transacts, dependent: :destroy
  has_many :financial_transactions, through: :cat_transacts

  validates :name, presence: true, length: { maximum: 250 }

  def total(category_id)
    financial_transactions.joins(:cat_transacts).where(cat_transacts: { category_id: }).sum('financial_transactions.amount')
  end
end

app/models/financial_transaction.rb
class FinancialTransaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :cat_transacts, dependent: :destroy
  has_many :categories, through: :cat_transacts

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  has_many :financial_transactions, foreign_key: 'author_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Devise::Controllers::Helpers


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
  end

  protected

  def after_sign_up_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.new(category_params)
    @category.user = current_user
    @category.icon.attach(params[:category][:icon])

    if @category.save
      flash[:success] = 'category created successfully'
      redirect_to users_path(user_id: current_user.id)
    else
      flash[:alert] = 'error creating category'
    end
  end

  def show
    @user = current_user
    @category = Category.find(params[:id])
    @cattransaction = @category.cat_transacts.includes([:financial_transaction])
    @total = @cattransaction.sum(:amount)
  end

  def destroy
    @category = category.find(params[:id])
    @category.destroy!
    flash[:notice] = 'category has been successfully deleted!'
    redirect_to user_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/financial_transactions_controller.rb
class FinancialTransactionsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @financial_transaction = @category.financial_transactions.order(created_at: :desc)
  end

  def new
    @financial_transaction = current_user.financial_transactions.new
    @category = Category.find(params[:category_id])
  end

  def create
    @financial_transaction = current_user.financial_transactions.new(financial_transaction_params.slice(:name, :amount))

    if @financial_transaction.save
      @cat_transact = CatTransact.new(financial_transaction_id: @financial_transaction.id, category_id: params[:financial_transaction][:category_id])

      if @cat_transact.save
        redirect_to user_category_financial_transactions_path(current_user, params[:financial_transaction][:category_id]),
                    notice: 'financial_transaction created successfully'
      end
    else
      render :new
    end
  end

  def destroy
    @financial_transaction = FinancialTransaction.find(params[:id])
    @financial_transaction.destroy!
    flash[:notice] = 'Transaction has been successfully deleted!'
    redirect_to user_category_path(@financial_transaction.category_id)
  end

  private

  def financial_transaction_params
    params.require(:financial_transaction).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @categories = Category.includes(:financial_transactions).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_transacts_helper.rb
module CatTransactsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/financial_transactions_helper.rb
module FinancialTransactionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/new.html.erb
<div class="container">
<nav class="header cool">
  <p>Create new category</p>
</nav>
<div class="sign_in_fields">
<%= form_with model: @category, url: user_categories_path do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :icon %>
    <%= form.file_field :icon %>
  </div>
  <div class="actions">
    <%= form.submit %>
  <a href="<%= users_path %>"><button class="page-btns"> Back </button></a>
  </div>
<% end %>
</div>
</div>

app/views/financial_transactions/index.html.erb
<div class="container">
<div class="group_holder">
  <div class="group_card">
    <div class="card_element">
      <div class="picture_holder">
      <p class="Image_icon"><%= image_tag @category.icon %></p>
      </div>
      <div class="name_holder">
        <h5 class="category_name">
          <%=@category.name%>
        </h5>
        <p class="detail_description">A financial transaction is an agreement, or communication, between a buyer and seller to exchange goods, services, or assets for payment.</p>
      </div>
    </div>
    <hr>
    <div>
      <% @financial_transaction.each do |transact| %>
        <div class="transaction">
          <p>Transaction No <%=transact.id%></p>
          <div class="transaction_detail">
            <p><%=transact.created_at.strftime('%d %B %Y')%></p>
            <p>$<%=transact.amount%></p>
          </div>
        </div>
      <% end %>
    </div>
    <hr>
    <div class="total_transaction">
      <h5 class="total_font">TOTAL PAYMENT</h5>
      <h5 class="total_font">$<%=number_with_delimiter(@category.total(@category.id))%></h5>
    </div>
  </div>
</div>
<div class="navigation_link">
<button class= "page-btns" ><%= link_to 'Create New Transaction', new_user_category_financial_transaction_path(current_user,@category)%></button>
  <a href="<%= users_path %>"><button class="page-btns"> Back </button></a>
</div>
</div>
</div>

app/views/financial_transactions/new.html.erb
<div class="container">
<nav class="header">
  <p>Create new Transaction</p>
  </nav>

  <%= form_with model: [current_user, @category, FinancialTransaction.new], url: user_category_financial_transactions_path(current_user, @category) do |form| %>
    <div class="sign_in_holder">
      <div class="sign_in_fields">
        <%= form.text_field :name, placeholder: 'Name', required: true %>
        <%= form.number_field :amount, step: :any, required: true, placeholder: 'Amount' %>
        <%= form.collection_select :category_id, @current_user.categories, :id, :name, { prompt: 'Select a category' }, required: true %>
      </div>
      <div class="actions">
    <%= form.submit "Save transaction"%>
  <a href="<%= user_category_financial_transactions_path %>"><button class="page-btns">Back</button></a>
  </div>
    </div>
  <% end %>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <% if notice %>
  <p class="alert"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>
<%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light light">
  <a class="navbar-brand color" href="/">HAKI-BUDGET</a>
  <div class="navbar" id="navbarSupportedContent">
    <ul class="sign-in-up ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<% if user_signed_in? %> 
<div class="container">
 <div class="welcome"> Welcome, <%= @user.name %> </div> 
 <% if @categories.empty? %>
 <h2>Please add some category</h2>
 <% else %>
 <ul class="category-list">
   <% @categories.each do |category|%>
   <li class="category-list-items">
     <%= link_to user_category_financial_transactions_path(current_user, category.id) do %>
     <div class="category-items-details">
     <p class="Image"><%= image_tag category.icon %></p>
     <div class="time-description">
       <div class="category_description">
         <h2><%= category.name%></h2>
         <p><%= category.total(category.id)%></p>
        </div>
        <p><%=category.created_at.strftime('%d %B %Y')%></p>
        </div>
     </div>
     <% end %> 
     <% end %>
   </li>
   <% end %> 
 </ul>
 <button class="page-btns">
   <%= link_to 'Create New category', new_user_category_path(user_id:@user.id) %>
</button>
</div>
<% else %>
<div class="main_page container">
<h1>Welcome to your Budget Track </h1>
<p class="main_parag">This is a budget App that helps you to track your budget, it registers your transactions. 
if you like the app feature kindly give the project a star on <a href="https://github.com/hakichris"> GITHUB </a>, and follow us on <a href="https://linkedin.com/in/hakichris">LINKEDIN</a></p>
  </div>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? %> 
<div class="container">
 <div class="welcome"> Welcome, <%= @user.name %> </div> 
 <% if @categories.empty? %>
 <h2>Please add some category</h2>
 <% else %>
 <ul class="category-list">
   <% @categories.each do |category|%>
   <li class="category-list-items">
     <%= link_to user_category_financial_transactions_path(current_user, category.id) do %>
     <div class="category-items-details">
     <p class="Image"><%= image_tag category.icon %></p>
     <div class="time-description">
       <div class="category_description">
         <h2><%= category.name%></h2>
         <p><%= category.total(category.id)%></p>
        </div>
        <p><%=category.created_at.strftime('%d %B %Y')%></p>
        </div>
     </div>
     <% end %> 
     <% end %>
   </li>
   <% end %> 
 </ul>
 <button class="page-btns">
   <%= link_to 'Create New category', new_user_category_path(user_id:@user.id) %>
</button>
</div>
<% else %>
<div class="main_page container">
<h1>Welcome, to your Budget Track </h1>
<p class="main_parag">This is a budget App that helps you to track your budget, it registers your transactions. 
if you like the app feature kindly give the project a star on <a href="https://github.com/hakichris"> GITHUB </a>, and follow us on <a href="https://linkedin.com/in/hakichris">LINKEDIN</a></p>
  </div>
<% end %>